title: SETS
description: SETS project page.
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at

markdown: kramdown
kramdown:
  input: GFM

# Optional: keep URLs clean
permalink: pretty